on: workflow_dispatch

jobs:
  Say-Hi:
    runs-on: ubuntu-latest

    steps:
      - name: Job is triggered
        run: echo "You triggered the helloworld job"

      - name: printing Hello
        run: echo "WELLO HORLD"
      
  Say-Bye:
      runs-on: ubuntu-latest
  
      steps:
        - name: Save text
          run: echo "Bye" > bye.txt
        - name: Ba-Bye
          run: cat bye.txt
